version: '3.8'

services:
  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: "devdb"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"