http:
  host: 0.0.0.0
  port: 8000
  write-timeout: 5s
  read-timeout: 5s
  maxHeaderBytes: 1

postgres:
  host: postgres
  port: 5432
  user: pguser
  database: devdb
  ssl-mode: disable


insertTestData: true