### Освобождение от резервации
POST http://localhost:8000/api/releaseProducts
Content-Type: application/json

[
  "987",
  "321",
  "987",
  "789"
]

### Освобождение от резервации товара с преувелечением места (с ошибкой)
POST http://localhost:8000/api/releaseProducts
Content-Type: application/json

[
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "987",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "987"
]