### Резервирование товара
POST http://localhost:8000/api/reserveProducts
Content-Type: application/json

[
  "987",
  "789",
  "123"
]


### Резервирование товара с преувелечением места (с ошибкой)
POST http://localhost:8000/api/reserveProducts
Content-Type: application/json

[
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "987",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "321",
  "987"
]